Repository sur-lock/sur-lock, pull requests merged in 2021-09, with the labels that each got.

#2 기본 리액트와 타입스크립트 설정을 가져옵니다.
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/.npmrc
  frontend/.prettierrc.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/api/serverContext.ts
  frontend/src/components/index.ts
  frontend/src/index.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/index.ts
  frontend/src/pages/index.ts
  frontend/src/react-app-env.d.ts
  frontend/src/reportWebVitals.ts
  frontend/src/setupTests.ts
  frontend/src/store/index.ts
  frontend/src/style/GlobalStyle.ts
  frontend/src/style/reset.ts
  frontend/src/style/theme.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: enhancement

#3 theme요소를 재정의합니다
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/style/GlobalStyle.ts
  frontend/src/style/styled.d.ts
  frontend/src/style/theme.ts
Labels: enhancement

#4 리덕스 툴킷 설정을 마칩니다
  frontend/.eslintrc.js
  frontend/package.json
  frontend/src/index.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/store/authSlice.ts
  frontend/src/store/index.ts
  frontend/yarn.lock
Labels: 🎁 DONE, ⚛️ FE

#6 테마 설정을 위한 토글 버튼을 추가합니다.
  frontend/.eslintrc.js
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/ThemeToggle.tsx
  frontend/src/style/theme.ts
  frontend/yarn.lock
Labels: 🎁 DONE, ⚛️ FE, ⚒️ Feature

#8 스토리북 사용을 위한 기본 설정과 코드를 추가합니다
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/index.ts
  frontend/src/components/MainPageSlide/FirstSlide.tsx
  frontend/src/components/MainPageSlide/index.ts
  frontend/src/components/ThemeToggle/ThemeToggle.stories.tsx
  frontend/src/components/ThemeToggle/ThemeToggle.tsx
  frontend/src/components/ThemeToggle/index.ts
  frontend/src/components/index.ts
  frontend/src/pages/MainPage/MainPage.stories.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/index.ts
  frontend/src/pages/index.ts
  frontend/yarn.lock
Labels: 🎁 DONE, ⚛️ FE, ⚒️ Feature, 👀 Test

#13 feat : 설문조사생성페이지 기능구현, FAB구현
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/AnswerSurvey/AnswerSurvey.tsx
  frontend/src/components/AnswerSurvey/index.ts
  frontend/src/components/AnswerSurveyWithImg/AnswerSurveyWithImg.tsx
  frontend/src/components/AnswerSurveyWithImg/index.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/OptionalSurvey/OptionalSurvey.tsx
  frontend/src/components/OptionalSurvey/index.ts
  frontend/src/components/OptionalSurveyWithImg/OptionalSurveyWithImg.tsx
  frontend/src/components/OptionalSurveyWithImg/index.ts
  frontend/src/pages/CreateSurvey/CreateSurvey.tsx
  frontend/yarn.lock
Labels: 🎁 DONE, ⚛️ FE, ⚒️ Feature

#14 이미지 조회
  backend/.gitignore
  backend/pom.xml
  backend/src/main/java/com/surlock/api/ApiError.java
  backend/src/main/java/com/surlock/api/ApiResult.java
  backend/src/main/java/com/surlock/api/ImageRestController.java
  backend/src/main/java/com/surlock/common/util/MimeMap.java
  backend/src/main/java/com/surlock/configure/ControllerExceptionHandler.java
  backend/src/main/java/com/surlock/entity/Image.java
  backend/src/main/java/com/surlock/exception/NotFoundException.java
  backend/src/main/java/com/surlock/repository/ImageRepository.java
  backend/src/main/java/com/surlock/service/ImageService.java
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/application-prod.properties
  backend/src/main/resources/application.properties
  backend/src/main/resources/images/java-icon.png
  backend/src/main/resources/images/test.jpg
  backend/src/main/resources/import.sql
Labels: 🍃 BE, ⚒️ Feature

#17 이미지 업로드 및 조회
  backend/.gitignore
  backend/src/main/java/com/surlock/api/ImageRestController.java
  backend/src/main/java/com/surlock/common/util/ExtMimeUtils.java
  backend/src/main/java/com/surlock/common/util/MimeMap.java
  backend/src/main/java/com/surlock/entity/Image.java
  backend/src/main/java/com/surlock/exception/FileCreateException.java
  backend/src/main/java/com/surlock/service/ImageService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/images/java-icon.png
  backend/src/main/resources/images/test.jpg
  backend/src/main/resources/import.sql
  backend/upload-images/test.jpg
Labels: 🍃 BE, ⚒️ Feature

#18 백엔드 API 문서화 (swagger)
  backend/src/main/java/com/surlock/configure/SwaggerConfig.java
Labels: 🍃 BE, ⚒️ Feature

#20 Feat : 데이터 바인딩
  frontend/src/components/AnswerSurvey/AnswerSurvey.tsx
  frontend/src/components/AnswerSurveyWithImg/AnswerSurveyWithImg.tsx
  frontend/src/components/OptionalSurvey/OptionalSurvey.tsx
  frontend/src/components/OptionalSurveyWithImg/OptionalSurveyWithImg.tsx
  frontend/src/components/SurveyTitle/SurveyTitle.tsx
  frontend/src/components/SurveyTitle/index.ts
  frontend/src/components/index.ts
  frontend/src/pages/CreateSurvey/CreateSurvey.tsx
Labels: 🎁 DONE, ⚛️ FE, ⚒️ Feature

#24 사용자의 스크롤을 유도할 수 있는 컴포넌트를 추가합니다
  frontend/src/components/Footer/Footer.stories.tsx
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/InducingScroll/InducingScroll.stories.tsx
  frontend/src/components/InducingScroll/InducingScroll.tsx
  frontend/src/components/InducingScroll/index.ts
  frontend/src/components/MainPageSlide/FirstSlide.tsx
  frontend/src/components/MainPageSlide/SecondSlide.tsx
  frontend/src/components/MainPageSlide/ThirdSlide.tsx
  frontend/src/components/index.ts
Labels: 🎁 DONE, ⚛️ FE, ⚒️ Feature
