Repository sur-lock/sur-lock, pull requests merged in 2021-10, with the labels that each got.

#25 설문 응답페이지
  frontend/src/App.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Response/ResponseAnswer/ResponseAnswer.tsx
  frontend/src/components/Response/ResponseAnswer/index.ts
  frontend/src/components/Response/ResponseAnswerWithImg/ResponseAnswerWithImg.tsx
  frontend/src/components/Response/ResponseAnswerWithImg/index.ts
  frontend/src/components/Response/ResponseOption/ResponseOption.tsx
  frontend/src/components/Response/ResponseOption/index.ts
  frontend/src/components/Response/ResponseOptionWithImg/ResponseOptionWithImg.tsx
  frontend/src/components/Response/ResponseOptionWithImg/index.ts
  frontend/src/components/Response/index.ts
  frontend/src/components/index.ts
  frontend/src/pages/ResponseSurvey/ResponseSurvey.tsx
  frontend/src/pages/ResponseSurvey/index.ts
  frontend/src/pages/index.ts
Labels: 🎁 DONE, ⚛️ FE, ⚒️ Feature

#26 카카오 로그인 기능 구현
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/public/index.html
  frontend/src/components/Header/Header.tsx
  frontend/src/store/authSlice.ts
Labels: ⚛️ FE, 🎡 DOING, ⚒️ Feature

#27 첫번째 슬라이드를 수정합니다.
  frontend/src/components/MainPageSlide/FirstSlide.tsx
  frontend/src/static/image/background.png
  frontend/src/static/image/index.ts
Labels: 🎁 DONE, ⚛️ FE, ⚒️ Feature

#28 블록체인으로부터 데이터 읽기
  frontend/.env.development
  frontend/.env.production
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/OptionalSurvey/OptionalSurvey.tsx
  frontend/src/components/OptionalSurveyWithImg/OptionalSurveyWithImg.tsx
  frontend/src/pages/CreateSurvey/CreateSurvey.tsx
  frontend/src/pages/ResponseSurvey/ResponseSurvey.tsx
Labels: ⚛️ FE, 🎡 DOING, ⚒️ Feature

#34 전반적인 디자인을 추가하고 설문조사 결과 페이지의 데이터를 불러옵니다
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/AnswerSurvey/AnswerSurvey.tsx
  frontend/src/components/AnswerSurveyWithImg/AnswerSurveyWithImg.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/OptionalSurvey/OptionalSurvey.tsx
  frontend/src/components/OptionalSurveyWithImg/OptionalSurveyWithImg.tsx
  frontend/src/components/Response/ResponseAnswer/ResponseAnswer.tsx
  frontend/src/components/Response/ResponseAnswerWithImg/ResponseAnswerWithImg.tsx
  frontend/src/components/Response/ResponseOption/ResponseOption.tsx
  frontend/src/components/Response/ResponseOptionWithImg/ResponseOptionWithImg.tsx
  frontend/src/components/SurveyTitle/SurveyTitle.tsx
  frontend/src/pages/CreateSurvey/CreateSurvey.tsx
  frontend/src/pages/ResponseSurvey/ResponseSurvey.tsx
  frontend/src/pages/SurveyResult/SurveyResult.tsx
  frontend/src/pages/SurveyResult/index.ts
  frontend/src/pages/index.ts
  frontend/src/style/GlobalStyle.ts
  frontend/src/style/theme.ts
  frontend/yarn.lock
Labels: ⚛️ FE, 🎡 DOING, ⚒️ Feature

#36 설문 생성 또는 응답 제출 시 로딩중 띄우기
  exec/README.md
  frontend/src/components/FullscreenSpinner/FullscreenSpinner.stories.tsx
  frontend/src/components/FullscreenSpinner/FullscreenSpinner.tsx
  frontend/src/components/FullscreenSpinner/index.ts
  frontend/src/components/SurveyTitle/SurveyTitle.tsx
  frontend/src/components/index.ts
  frontend/src/pages/CreateSurvey/CreateSurvey.tsx
  frontend/src/pages/ResponseSurvey/ResponseSurvey.tsx
Labels: ⚛️ FE, ⚒️ Feature
